const mongoose = require('mongoose')
require('dotenv').config()
mongoose.connect(process.env.DB)
.then(()=> console.log('Connected DB'))
.catch((err)=> console.log('You have a problem about connecting DB', err))